### ISSUE TITLE
Add option to remove type/value/suit display for player hands/cards.

### ISSUE THREAD

**Issue by OberusPing** [zeel01/monarch#16]
For game systems that just want to use the card UI to deal with cards as images (without corresponding suit/values), it would be great if there was a UI option to not display the boxes corresponding to suit/value/type when hovering over a card in a hand, since they would always be empty.

**Comment by zeel01** [comment]
Yes, I intend to make it such that if those values don't exist, the boxes just won't appear.

**Comment by zeel01** [comment]
Closed by 04e296ada035bc1404d8702588b2ba9e38607cda
