### ISSUE TITLE
Card faces with ( ) in filename not displaying when drawn from deck.

### ISSUE THREAD

**Issue by SkazzK** [zeel01/monarch#17]
I scanned multiple adjacent cards, then used an online tool to cut the resulting image. They ended up in several zip files, the images in these zip files having the same filenames (row1column1.jpg and so on). I unzipped them into one folder, having windows automatically rename the second batch from row1column1.jpg to row1column1 (2).jpg and so on.

The cards that have parentheses in the filename show up blank when drawn to a hand.

**Comment by zeel01** [comment]
Ah, interesting. I think I know why, and how to correct it.

I would consider it a best practice to avoid parenthesis and spaces in file names, but I should be able to correct for this in the next release.

**Comment by SkazzK** [comment]
I've come to agree with you. While images with spaces do display correctly, the %20 in the name is slightly off-putting.
