### ISSUE TITLE
Red warning message in console

### ISSUE THREAD

**Issue by Artemisthemp** [zeel01/monarch#27]
Enabling Monarch 0.2.4 on Foundry 9.245 with 5e 1.5.7 will cause the error message below to appear in the console.

VM43338:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at loadWindowPositions (utils.js:15:25)
    at Module.restoreWindows (utils.js:26:2)
    at monarch.js:49:8
    at Function._call (foundry.js:294:14)
    at Function.callAll (foundry.js:253:12)
    at Game.setupGame (foundry.js:5566:11)
    at async Game._initializeGameView (foundry.js:6498:5)
    at async Game.initialize (foundry.js:5430:5)

**Note:** Test on a fresh world with no other modules enable.

**Comment by zeel01** [comment]
This looks like a data corruption issue. What do you get if you do the following in the console:
```js
window.localStorage.getItem("monarch-windows");
```
This should be a valid JSON string, but if it isn't you can try doing:
```js
window.localStorage.setItem("monarch-windows", "{}")
```
Which should clear it and set it to a valid string.

**Comment by Artemisthemp** [comment]
I didn't get any error on my local machine, yet the error show up on my Molten Hosting Foundry.

window.localStorage.getItem("monarch-windows");  - Return a null
window.localStorage.setItem("monarch-windows", "{}") - Returned a undefined.

I finally decided to try uninstalling Monarch, then reinstalled it before launching the world again. - No error in the console.

Seems the issue is fixed, so going to close it.
