### ISSUE TITLE
Add hide property to CardControl

### ISSUE THREAD

**Issue by admiralnlson** [zeel01/monarch#38]
Hello @zeel01,

For Castle Falkenstein, I would like to be able to fully hide (not just disable) a CardControl based on (card, container) conditionals.

Could you please support a `hide?` property in `CardControl`?

```
export type CardControl = {
  [...]
  hide?: boolean | booleanCallback;
  [...]
};
```

Alternatively, I suppose `class?` could also be used to hide a CardControl via CSS, but incidentally `class?` is only a
```
class?: string;
```
and not a
```
class?: string | stringCallback;
```

**Comment by zeel01** [comment]
You wouldn't want to use `class` as that's how the buttons are located to add their event listeners. This is why it isn't dynamic - all the listeners for the same control should be the same.

That being said, you could use the combination of the `class` and the `data-disabled` attribute to apply custom styles to the control. 

```css
.card-control.my-control[data-disabled] {
    display: none;
} 
```
That being said... *yeah* I guess I probably should add a `hide` option on controls. 

But my rationale for not having done so is this: It means the exact layout of controls on each card can vary. For instance, if you have a set of controls A, B, C, D and A might be hidden, then users might mistakenly click the first button expecting it to be A, but instead it was B. 

*However* I can also see a counter example. If it's clear that certain cards don't have the same kinds of actions for game reasons (Like spell cards, monster cards, item cards, etc.) then it would be intuitive that they would not all need all the same controls. 

So I guess my long-winded answer is: Yes, all add `hide`. Though it's already possible to do this with CSS if you want.

**Comment by admiralnlson** [comment]
Thanks for sharing the CSS work-around.
Since the .card-hud remains, I'll need to teak the CSS a little more though.
![image](https://user-images.githubusercontent.com/4472669/154438969-bd4d57d7-7cb9-4e98-91f4-33771a90f6ba.png)


> If it's clear that certain cards don't have the same kinds of actions for game reasons (Like spell cards, monster cards, item cards, etc.)

Precisely my use case. Castle Falkenstein uses two decks (Fortune and Sorcery) which are used into two independent game mechanics.

```
      components.controls.push({
        tooltip: "castle-falkenstein.cards.discard",
        icon: "cf-card-discard",
        class: "discard-card",
        /* FIXME Cannot 'hide' CardControls in Monarch yet (https://github.com/zeel01/monarch/issues/38).
                 For the time being, the Discard control will be 'disabled' only in Fortune hands.
        hide: (card, container) => {
          const handProperties = container.getFlag("castle-falkenstein", "handProperties");
          return handProperties.type != "sorcery";
        },*/
        disabled: (card, container) => {
          const handProperties = container.getFlag("castle-falkenstein", "handProperties");
          return handProperties.type != "sorcery";
        },
        onclick: async (event, card, container) => {
          const handProperties = await container.getFlag("castle-falkenstein", "handProperties");
          if (handProperties.type == "sorcery") {
            card.pass(CastleFalkenstein.sorceryDiscardPile);
          }
        }
      });
```
