### ISSUE TITLE
It is possible for the window location data in localStorage to be invalid, leading to a JSON parsing error on load.

### ISSUE THREAD

**Issue by DanielBoettner** [zeel01/monarch#39]
Thanks for working on this module. Well crafted and styled.

When I load FoundryVTT with a player user I get the following error in the console.

## Error message
```js
Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at loadWindowPositions (utils.js:15:25)
    at Module.restoreWindows (utils.js:26:2)
    at Function.onReady (Monarch.js:219:9)

  | loadWindowPositions | @ | utils.js:15
-- | -- | -- | --
  | restoreWindows | @ | utils.js:26
  | onReady | @ | Monarch.js:219
  | await in onReady (async) |   |  
  | _call | @ | foundry.js:294
  | callAll | @ | foundry.js:253
  | setupGame | @ | foundry.js:5566
  | await in setupGame (async) |   |  
  | _initializeGameView | @ | foundry.js:6498
  | _initializeView | @ | foundry.js:6474
  | initialize | @ | foundry.js:5430
  | await in initialize (async) |   |  
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:511
  | 🎁libWrapperInit | @ | libWrapper-api.js:793
  | await in 🎁libWrapperInit (async) |   |  
  | 🎁Game.prototype.initialize#0 | @ | libWrapper-wrapper.js:187
  | window.addEventListener.once | @ | foundry.js:62436
```
Not sure if this connected to the players. Or if this could also happen as GM.
with the GM account however, I do not get this error.

## further resources
https://stackoverflow.com/questions/30621802/why-does-json-parse-fail-with-the-empty-string

### Old
https://github.com/zeel01/monarch/blob/04badbf35ac75f738cbb65142e3025c8134ade09/scripts/utils.js#L14

### New 
```js
const data = window.localStorage.getItem("monarch-windows") || '{}'; 
```

## Explanation of the change
When using the "Old" from above in 
https://github.com/zeel01/monarch/blob/04badbf35ac75f738cbb65142e3025c8134ade09/scripts/utils.js#L15
The variable `data` is an empty string. Which `JSON.parse` can't parse.

Using either `"{}"` or maybe `'""'` (double quotes in single quotes) should yield the desired behavior. 
This should also make the `|| {}` in line 15 obsolete I think. As data will always be a parsable string.
This could be wrong if `window.localStorage.getItem("monarch-windows")` will return something else then valid json or null.

**Comment by zeel01** [comment]
What's really confusing is why this error can happen in the first place. Have you tried reading out the storage object to see what's inside of it and why it doesn't appear to be valid JSON?

Your suggestion though is a good one, but does this error only happen if the value is empty? Or is it happening because some invalid data was stored that fails to parse but won't be falsy to the `||` operator?
