### ISSUE TITLE
Allow for macros in card descriptions

### ISSUE THREAD

**Issue by mudgw2** [zeel01/monarch#41]
Would be neat if a player could view their card and in the description it requests them to click to roll against a skill (for example).  This could tie into the display card in chat enhancement allowing players to draw cards, roll against them and display their process in chat and result!

**Comment by zeel01** [comment]
Do you mean like the way Items allow for inline rolls in their descriptions? Cards don't really support rich text unfortunately, so it would be odd for Monarch to add rich text.

**Comment by mudgw2** [comment]
Ah, ok bummer.  I was attempting to translate pathfinder cards into the system from a deck I own.  And the cards when drawn request the user to perform various skill checks to see if they succeed.  The game deploys in a 3x3 grid of these cards..and was seeing if monarch could pull that off.
