### ISSUE TITLE
Card descriptor width is too narrow

### ISSUE THREAD

**Issue by BrotherSharper** [zeel01/monarch#42]
The card descriptor width is too narrow to hold Japanese characters or anything more than 4 English letters. It would be nice if this could be made a little big wider.
![issue](https://user-images.githubusercontent.com/41280723/154794008-6bd4df18-2ae6-4211-80cc-eede83bc754a.png)

**Comment by zeel01** [comment]
The label is a flex, so it shouldn't matter how long it is, but the browser is minimizing its length by using word-wrapping. I've added the `white-space: nowrap;` property, so now it will prefer not to add line breaks in the labels which should resolve this issue.
