### ISSUE TITLE
Request: Hide labels if fields are empty

### ISSUE THREAD

**Issue by Joshmvii7** [zeel01/monarch#43]
Requesting to not display labels on cards for fields that are blank like suit/value. 

Example images.
![image](https://user-images.githubusercontent.com/99048395/155390721-82e1188d-8554-450c-81d1-86146d627fe5.png)
![image](https://user-images.githubusercontent.com/99048395/155390755-697da39f-2735-403a-9612-1a4c204fe159.png)

**Comment by zeel01** [comment]
You can disable those badges in the module settings.

**Comment by Joshmvii7** [comment]
@zeel01 

I found the settings for suit/value, but there's no way I can see to turn off the name field, which means in the deck itself there's still a field for name showing up even when it's blank.

![image](https://user-images.githubusercontent.com/99048395/155399554-281fe5a6-5270-4d5f-a2ac-c4c3c8d8ef7d.png)

**Comment by zeel01** [comment]
I'm of a split opinion here. I see what you are doing, the image has the name so you are relilying on that. But for accessibility and ease of use name should never be blank. Without it, the card name may be difficult to read. 

I do get how having the name over the card image might not be desired. You *could* remove it via the API of course.

I could add a setting to disable name, but I don't love that. It's only a badge in the deck/pile anyway. In hand, the name is in the tooltip above the card.

**Comment by Joshmvii7** [comment]
Sure. I understand your point there, and it's no big deal at all either way. Like you said, it's only in the deck, not in the hand where the players are viewing it for use. I love the module, thanks for taking the time to look at this!
