### ISSUE TITLE
Use entire card surface to open play card/expanded view

### ISSUE THREAD

**Issue by MarkPearce** [zeel01/monarch#46]
rather than a small button in the bottom left corner, use the entire card surface as the hit area for the expanded view to play card.

![issue_playcard](https://user-images.githubusercontent.com/6976378/155422661-1ed218de-6dc6-4a42-863f-b36af8d76fa6.png)

**Comment by zeel01** [comment]
The primary card click action is to open the Card Config sheet for the card (it is recommended that you set Monarch as your Card Config sheet). However, this action is easily modified via the API [via a hook](https://github.com/zeel01/monarch#clickMonarchCard).

The standard play button is not intended as the way to *view* a card though, so if the goal is to view a card full sized you just need to use Monarch as the Card sheet as mentioned above.

**Comment by MarkPearce** [comment]
ah cool.... an API you say?! let me give that a shot. A desugner trying to
code... what could go wrong?

 Thanks for the examples. (and great mod)
