### ISSUE TITLE
Consider using a single face toggle button when a card has only two faces, rather than the standard face cycler.

### ISSUE THREAD

**Issue by MarkPearce** [zeel01/monarch#47]
Replace the tiny split button with a single "Flip card" button

if the card face is visible show the card back
else
show the card face

![issue_flip](https://user-images.githubusercontent.com/6976378/155422770-f5a184af-8162-42c7-b0a5-5dcb52504f26.png)

**Comment by zeel01** [comment]
Core intentionally uses two buttons to facilitate cards with more than just two faces. While this may be niche, I can't switch to using a toggle and lose the base functionality.

However, a module could easily utilize the Monarch API to remove the standard buttons and replace them with a single toggle.

I might consider a PR that adds the above as an optional setting, but I'm on the fence about it.

**Comment by MarkPearce** [comment]
if #faces < 2

**Comment by MarkPearce** [comment]
or at least make the hit area on the split button larger....

**Comment by zeel01** [comment]
> if #faces < 2

A realistic compromise. Ill consider it.
