### ISSUE TITLE
Cant pass or discard cards

### ISSUE THREAD

**Issue by Gabbaoma** [zeel01/monarch#55]
Hello, I recently ran into an issue. Whenever a player or I try to discard or pass a card, there is an error message and the card is not passes/discarded. I already recollected all cards from the stack, but the error keeps showing up with new drawn or dealt cards. Do you have an idea how to resolve that issue? Thanks in advance!

Monarch V0.4.1 and FoundryVTT V9.268.

Error within FoundryVTT when trying to pass a card:
you may not pass Card 16hIz2BAG1I5Rc4y which has already been drawn

Console when trying to discard a card, no error message within foundry:
foundry.js:14276 
        
       Uncaught (in promise) Error: You may not pass Card 16hIz2BAG1I5Rc4y which has already been drawn
[Detected 1 package: monarch]
    at Cards.pass (foundry.js:14276:36)
    at Card.pass (foundry.js:14037:39)
    at Object.onclick [as discard-card] (Components.js:179:35)
    at MonarchCardsConfig.js:105:32
    at DOMTokenList.forEach (<anonymous>)
    at MonarchHand._onControl (MonarchCardsConfig.js:103:20)
    at HTMLAnchorElement.<anonymous> (MonarchCardsConfig.js:65:52)

**Comment by zeel01** [comment]
Does this happen if Monarch is the *only* package enabled? Does this happen for all hands and decks? What happens if you create a new deck, does it have the same issues?

**Comment by zeel01** [comment]
Actually, another question: what happens when to pass or discard a card *without* using Monarch? Does it work correctly with the core card sheets?

**Comment by Gabbaoma** [comment]
> Does this happen if Monarch is the _only_ package enabled? Does this happen for all hands and decks? What happens if you create a new deck, does it have the same issues?

Just tried it. Issue does happen with Monarch only and also for all decks and hands. Even new hands, piles or decks.

You were correct with the core card sheets. I didnt even think of disabling monarch first. Issue does remain... Do you know how to save a export and import a deck without having to redo every card?

**Comment by zeel01** [comment]
Unfortunately I'm not sure what the issue is caused by. You may need to ask for assistance on the Foundry VTT Discord server https://discord.gg/foundryvtt

Be sure to show them the error message with no modules enabled (the first thing they are going to ask is if you have modules in use). They may be able to help find the issue/recover from it.

**Comment by Gabbaoma** [comment]
Will do. Thank you!
